#!/bin/bash
# cf-optimize-refresh.sh — refresh ~/proxy-bin/cf-optimized.txt: a curated
# list of Cloudflare-fronted "preferred" domains (from cf.090227.xyz's own
# reference list) plus live per-carrier optimized IPs from its API. Consumed
# by subserver.py as extra front (CF -> CloudShell) nodes, merged with
# front-domains.txt (see _front_domain_entries there).
#
# Safe to re-run; on fetch failure it still writes the static domain list (an
# already-slow IP source just means fewer entries this cycle, never a wiped
# file — subserver.py's dedupe means front-domains.txt entries always win
# over these).
#
# Called periodically from supervise.sh (default: every 2 days, see
# CF_REFRESH_INTERVAL there). Run manually to seed/update it immediately:
#   bash ~/proxy-bin/cf-optimize-refresh.sh
set -u
BIN="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$BIN/cf-optimized.txt"
TMP="$OUT.tmp.$$"

# Curated CF-fronted "preferred domain" list — these only ever get contacted
# by DNS resolution (their real service is never touched); the vless node's
# TLS SNI/Host still point at your own tunnel hostname, so Cloudflare's edge
# routes the connection to your Cloud Shell exactly like any other front
# entry. Stable, no fetch needed.
DOMAINS=$'cf.090227.xyz CF优选·090227\nwww.visa.cn 伪装·VISA\ntime.is 伪装·TimeIs\nsaas.sin.fan CF优选·MIYU\nbestcf.030101.xyz CF优选·移动'

IPS=""
for src in ct cu cmcc; do
  out=$(curl -s -m 8 "https://cf.090227.xyz/$src?ips=2" 2>/dev/null)
  [ -z "$out" ] && continue
  while IFS='#' read -r ip tag; do
    [ -z "$ip" ] && continue
    tag=$(echo "${tag:-CF优选}" | tr -d ' ')
    IPS+="$ip IP优选·$tag"$'\n'
  done <<<"$out"
done

{
  echo "# auto-generated by cf-optimize-refresh.sh — $(date -u '+%F %T UTC')"
  echo "# do not hand-edit; permanent custom entries belong in front-domains.txt"
  echo "$DOMAINS"
  [ -n "$IPS" ] && printf '%s' "$IPS"
} > "$TMP" && mv "$TMP" "$OUT"
